# Generated by Django 5.1.6 on 2025-03-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_post',
            field=models.BooleanField(default=False),
        ),
    ]
