# Generated by Django 5.1.6 on 2025-03-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
