# Generated by Django 5.1.6 on 2025-03-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
