# Generated by Django 5.1.6 on 2025-03-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='main_post',
        ),
    ]
