# Generated by Django 5.1.6 on 2025-03-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_blog_main_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
